# Generated by Django 5.1.7 on 2025-04-05 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='score',
            new_name='grade',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance'),
        ),
    ]
