# Generated by Django 5.1.7 on 2025-04-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_teacher_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='grade',
            new_name='score',
        ),
    ]
